### ISSUE TITLE
Lil Design Update Request List

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/532_Group_22#107]
- [x] Center title
- [x] Reduce size of title slightly
- [ ] Different title colour background (?)
- [x] Add padding between tabs and tab content (plots, dropdowns etc) for both tabs
- [ ] Reduce size of line breaks on tab1
- [ ] Add padding between radiobuttons

**Comment by spentelow** [comment]
Ewwww... you want to centre the title?  That's gross.

**Comment by spentelow** [comment]
I've come around to the idea of centred titles.
