### ISSUE TITLE
Update repo folder structure

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/532_Group_22#17]
We might want to consider updating the folders. For instance, there are 3 image files for the sketch which should probably be in a folder. Just not sure what to name it :P
If we change the location of the image files we need to remember to update the references in the README and any other document that links to them.

**Comment by sbabicki** [comment]
Certainly data should be moved to its own folder. And maybe the proposal as well? Open to suggestions on this one.

**Comment by IfyAnene7** [comment]
I think the pdf and png files should also be in a folder, maybe "images".
