### ISSUE TITLE
Teamwork Contract

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/532_Group_22#2]

**Comment by CalSchafer** [comment]
I added a number of items to the teamwork contract. Take a look and we can discuss when we meet if there are issues

**Comment by sbabicki** [comment]
Looks great, I made a couple updates based on your suggestions. Is everyone good with publishing this on github?

**Comment by IfyAnene7** [comment]
I think the teamwork contract looks great. I also added an extra sentence to 'c'. Yeah, I'm fine with publishing it on Github.

**Comment by CalSchafer** [comment]
If we were to publish it on Github, I think we should remove it when we finish the project. The contract has too many personal details (strengths, weaknesses, interets)

**Comment by sbabicki** [comment]
We could also put a link to the google doc instead and then just change the
permissions when the project is over. That way the history won't be
available.

**Comment by spentelow** [comment]
All looks good to me.  My vote is for just leaving it on google docs to keep things simple.

**Comment by sbabicki** [comment]
Added a link to the README, we can include the link when we submit to canvas as well. I've changed the settings so it is viewable with a link, once the project is over I can change the settings so only we can view it.
