### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/532_Group_22#40]
Hi Group 22,

- I enjoyed reading your proposal. It was well written and included necessary details in appropriate detail. 
- I like how there is an order to how the user would use the dashboard and a reason behind how you set it up. The dashboard concept is clear and well designed.

- Tab 1: I am worried the text in the bar graph might be too small to read if you show all the data. Subsetting or a scroll bar might help the used look at the data easier. Where will you put the legend for the choropleth map?
- Tab 2: will there be a max number of CMAs Sarah can select to compare?
- Will the abbreviation CMA be explained anywhere in the dashboard?

**Comment by sbabicki** [comment]
Thanks @ahofmann4!

For Tab 2, would you suggest we set a maximum? I would be okay with allowing Sarah to select as many as she wants, but I'm also okay to limit the number.

**Comment by ahofmann4** [comment]
I don't think you need to make that decision now. And it'll be easier for
me to give feedback once I can see how it looks for M2.

**Comment by calsvein** [comment]
Addressing your feedback:

Tab 1: I am worried the text in the bar graph might be too small to read if you show all the data. Subsetting or a scroll bar might help the used look at the data easier. Where will you put the legend for the choropleth map?

**Implemented - Our bar graph has a scroll bar.**
**Not implemented yet - The choropleth map won't require a legend (it should be apparent based on what dropdowns the user has selected), but we will have tooltips to display some information.**


Tab 2: will there be a max number of CMAs Sarah can select to compare?

**N/A - there will not be a max number of CMAs to select from. A graph will only start with one CMA, and the user will have the flexibility to remove selections if the graph becomes too noisy.**

Will the abbreviation CMA be explained anywhere in the dashboard?

**This will be addressed in a future release

**Comment by sbabicki** [comment]
Thanks again for your feedback @ahofmann4. 
As of Milestone 4 we have implemented the remaining issues in this thread that had not been addressed yet in prior releases: increasing the height of the CMA plot so that it shows all the data and adding a legend in the bottom left corner of the choropleth.
