### ISSUE TITLE
add colors to bar chart by province

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/532_Group_22#53]
I think adding the ability to filter by provinces would be cool. That way the CMA barplot on the right won’t be as long, we would just show CMAs in the provinces selected. It would also help for the choropleth since it will change the scale based on only the province of interest. 

This could be implemented as a multi-select dropdown. Let me know in the comments if you like the idea or not!

**Comment by calsvein** [comment]
As discussed, this would be an optional feature that a user could turn on and off

**Comment by sbabicki** [comment]
Added feature to display highlighting when hovering over a specific province in the choropleth. This can easily be adjusted if we want to change it to be on click instead.
