### ISSUE TITLE
Peer feedback from Group21

### ISSUE THREAD

**Issue by chuangw6** [UBC-MDS/532_Group_22#67]
Hi, Group 22,
Hope you are doing great. This is frank from group 21. After looking at your proposal and the dashboard you have been working on, I am really interested in this project. Here is my feedback on your milestone2 [release](https://github.com/UBC-MDS/532_Group_22/tree/0.2.1).

### `README.md` file
- As a potential user of your app, I really like the way you wrote the readme file. It has a clear structure and sections are well explained and organized. 
- For the screenshot that you included in the readme file, I think it would be great to include the screenshot of your real app interface instead of the prototype given that it was milestone2.
- For the convenience of potential contributors who are interested in contributing to your project, it would be great to include the instructions on how they can run the app, and suggestions on what aspects they can contribute to for the project.

### `proposal.md` file
This file looks great to me.

### dashboard interface
- It's great to see a lot of interactivities on all plots on your dashboard interface.
- However, regarding usability, I think the appearance can be improved. For example, 
    - the font of the two tabs could be bigger & bolded. 
    - You can also add more white space between filters.
    - would be great if you add a side note to explain what the empty plots mean based on user selections (e.g. no data).

Thank you! Let me know if you have any questions or want to have a further discussion with me.

**Comment by sbabicki** [comment]
Hi @chuangw46 , thank you for your feedback! 

We have incorporated your feedback in the latest version of our app.
