### ISSUE TITLE
Setup app reviews with Heroku (Optional)

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/532_Group_22#72]
Heroku has a neat functionality where you can set it up to atomically deploy branches when PRs are opened on GitHub. This way you can test the dashboard live while reviewing a PR without downloading your collaborator's branch and running it locally. Set up your repo accordingly and create at least one PR that triggers an auto-deployment. Link this PR in canvas-submission.html.

**Comment by spentelow** [comment]
Link to PR where App Reviews was used - https://github.com/UBC-MDS/532_Group_22/pull/103
